### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by sinhblue** [pacocp/MaskRCNN_blur_background#1]
I try this project but the output images are unexpected, they're blured all, not only the background,  the image segmentation may be not working. Can you help me. I'm a newbie

**Comment by pacocp** [comment]
Hi,

Is the object of the image a person? Right now everything is only set up to detect people. 

If not it is not going to be detected and therefore everything is going to be blurred.

**Comment by sinhblue** [comment]
Yes, my input image is the people object. I tried with one-person object and multiple too, but the output is the same, everything was blurred.

**Comment by sinhblue** [comment]
@pacocp I just download the project and run it, do I have to do anymore? If not, could you try it again and show me the output please? Thank you.
